
spring.datasource.url=jdbc:postgresql://localhost:5432/orderService
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081


jwt.secret=${JWT_SECRET}


resilience4j.circuitbreaker.instances.product-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.product-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.product-service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.product-service.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.product-service.sliding-window-size=10

management.endpoints.web.exposure.include=*
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always
